services:
  backend:
    image: spring-base-backend
    ports:
      - "8088:8088"

  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8088
    depends_on:
      - backend
